name = "BoxOptNewton"
uuid = "6b9d4377-42f2-4f3b-a4da-97523cb5d2a3"
authors = ["chriselrod <elrodc@gmail.com> and contributors"]
version = "1.0.0-DEV"

[compat]
julia = "1.6"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
